import { AppProvider } from "@/shared/contexts";
import "./globals.css";

export const metadata = {
  title: "Next.Js 13 Pro Boilerplate",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        {/* PWA meta tags */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#111111" />
        <meta name="application-name" content="Next.Js 13 Pro Boilerplate" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Next.Js 13 Pro Boilerplate" />
        <meta name="format-detection" content="telephone=no" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        {/* Social meta tags */}
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:url" content={process.env.NEXT_PUBLIC_SITE_URL} />
        <meta name="twitter:title" content="Next.Js 13 Pro Boilerplate" />
        <meta name="twitter:description" content="Best Next.Js 13 Pro Boilerplate in the world" />
        <meta name="twitter:image" content={`${process.env.NEXT_PUBLIC_SITE_URL}/icons/icon-512.png`} />
        <meta name="twitter:creator" content="@Rofran" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Next.Js 13 Pro Boilerplate" />
        <meta property="og:description" content="Best Next.Js 13 Pro Boilerplate in the world" />
        <meta property="og:site_name" content="Next.Js 13 Pro Boilerplate" />
        <meta property="og:url" content={process.env.NEXT_PUBLIC_SITE_URL} />
        <meta property="og:image" content={`${process.env.NEXT_PUBLIC_SITE_URL}/icons/icon-512.png`} />
      </head>
        <body>
          <AppProvider>
            {children}
          </AppProvider>
        </body>
    </html>
  );
}
