import { AppProvider } from "@/shared/contexts";
import type { NextWebVitalsMetric } from 'next/app';
import "./globals.css";

export const metadata = {
  title: "Next.Js 13 Pro Boilerplate",
  description: "Generated by create next app",
};

export function reportWebVitals({ id, name, label, value, startTime, attribution }: NextWebVitalsMetric) {
  console.log('Web Vitals', { id, name, label, value, startTime, attribution });
  
  // Use `window.gtag` if you initialized Google Analytics as this example:
  // https://github.com/vercel/next.js/blob/canary/examples/with-google-analytics/pages/_app.js
  // @ts-ignore
  window.gtag('event', name, {
    event_category:
      label === 'web-vital' ? 'Web Vitals' : 'Next.js custom metric',
    value: Math.round(name === 'CLS' ? value * 1000 : value), // values must be integers
    event_label: id, // id unique to current page load
    non_interaction: true, // avoids affecting bounce rate.
  })
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body>
          <AppProvider>
            {children}
          </AppProvider>
        </body>
    </html>
  );
}
